# Don't print a new line at the start of the prompt
add_newline = true

# format = """
# [⛊ ](bold cyan)$all
# """

# Replace the "❯" symbol in the prompt with "➜"❯▂❱ ➤
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❱❱❱](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green" ▂
error_symbol = "[❱❱❱](bold red)"

# [directory.substitutions]
# "~/Envs" = "Envs "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
# symbol = "⛟  "
# format = "pkg [$symbol$version](bold yellow) "

[cmd_duration]
# disabled = true

[nodejs]
# symbol = "[⬢](bold green)"
# disabled = true
# format = "is [$symbol$version](bold green)"

[line_break]
# disabled = true

[git_branch]
# symbol = "\uf126 "
# symbol = "\u22B7  "
# symbol = "\u2691 "
# symbol = "\u2618 "
# symbol = "[\u2D62](bold purple) "
# symbol = "[\u2731](bold purple) "


